# Primer workflow en Github Actions
name: Primer workflow

on:
  push:
    branches: 
       -develop
  workflow_dispatch:

jobs:
  ListsRepository:
    runs-on: ubuntu-latest 
    steps:
      - run: echo "El repositorio se llama ${{ github.repository }} "
